#!/bin/sh

#
#   /engineyard/bin/shoryuken
#
#   Author: Jim Neath (jneath@engineyard.com)
#

# must be root
if [[ "$(whoami)" != "root" ]]; then
  echo "Must be run as root"
  exit 1
fi

signal_worker() {
  result=0
  set_pid_from_file
  (( pid )) || return 0
  logger -t "monit-shoryuken[$$]" "Issuing kill with -$signal $pid"
  sleep_count=0
  kill -$signal $pid
}

# arguments 
app_name=$1 action=$2 rails_env=$3 worker_id=$4

# variables
app_root="/data/${app_name}/current"
worker_ref="shoryuken_${worker_id}"
pid_dir="/var/run/engineyard/shoryuken/${app_name}"
pid_file="${pid_dir}/${worker_ref}.pid"
log_file="${app_root}/log/${worker_ref}.log"
conf_file="/data/${app_name}/current/config/shoryuken.yml"
app_user=$(stat -L -c"%U" "${app_root}")

shoryuken="${app_root}/ey_bundler_binstubs/shoryuken"

export HOME="/home/${app_user}"

# change to current directory
cd "${app_root}"

# script usage
usage ()
{
  echo "Usage: $0 <app_name> {start|stop} <rails_env> <worker_id>"
  exit 1
}

# start shoryuken
start ()
{
  # check if process is already running
  if [[ -f $pid_file ]]; then
    pid=$(cat "${pid_file}")

    if [[ -d /proc/$pid ]]; then
      echo "${0} is already running (${pid})"
      exit 1
    else
      rm -f "${pid_file}"
    fi
  fi

  # start shoryuken
  sudo RAILS_ENV="${rails_env}" RUBY_ENV="${rails_env}" "${shoryuken}" -R -C  "${conf_file}" -P "${pid_file}" -L "${log_file}" &
  exit $?
}

# stop shoryuken
stop ()
{
  ALLOW_TIMEOUT=1
  signal="TERM"
  signal_worker
  exit $?
}

# sanity checks
[[ $# -ne 4 ]] && usage
[[ ! -L $app_root ]] && { echo "${app_root} does not exist"; exit 1; }
[[ ! -f $conf_file ]] && { echo "${conf_file} does not exist"; exit 1; }
[[ ! -d $pid_dir ]] && mkdir -p "${pid_dir}" && chown "${app_user}:${app_user}" "${pid_dir}"

# execute action
case "${action}" in
  start) start;;
  stop) stop;;
  *) usage;;
esac
